language: python
python:
  - "2.7"
  - "3.6"

env:
  - PLATFORMIO_PROJECT_DIR=examples/native-blink
  - PLATFORMIO_PROJECT_DIR=examples/stc-blink
  - PLATFORMIO_PROJECT_DIR=examples/stc-header

install:
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - pio pkg install --global --platform symlink://.

script:
  - platformio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false

  slack:
    rooms:
      secure: rj5uPo81WQHQ6o5hNkIwvptlQezVY6jjsdedqsTAPzRxDGGa3M8NdXJyPLmR2MgN7wDF0UctJC+btiedAcW1G1Szbi7YNTGPhEvUDcJAhTmDVBbNlviHO0xL77wQLXWmEZBLAIiHGGaVoE0wbCryVqCf7pHfK5q7FkgJ1t2tM2QtzBn8IZdAi05RqSuiq6rOZlevg3txUMji6kNaAu3OiqQQmQzDuTyELEi3G/nkqJ5Wze5KoY3ILxYhqCSplodptksZfE+b1o9rMgutNR0QlTORmzP2FM71TtlU9b68XB24Gc1nv49wHdhiZ/EnqAZfyDdFa4IoHPk+GleY0Nm2eCOTSdkbmMagtp8ZhZS9okHsWLhKHkJTNjGawUOHRy99jti1kEWf/Uici1rkqi4CJHbxr83cEFOjGYZYI4SQWBBKyYAB0uqAfRK6QUAQKwutjiyOSwtfzncWtVpP4bSLE2n8prt1Vhbphy8w9etyy+DjjqSgAj4Mr13k/HlaVxfm9OwU2qHtx/TkzA76tNe0af5DNsmDGl8nEV3sMmtT0SselSUkE5DWTag/RiEVM8fX/K+/gw8PnCmxiY28I9F0EisGlitUS19NbUA0nLIO/3V6E8heilzAhMxe3FYPil/0FdQQE/vT4tefofrg4fEV4l9mP3AFNB3yomGIx1h6Bfs=
    on_failure: always
    on_success: change
